# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e056932228b048ac37208711975fa2d7"
application_url = "https://trade-latest.onrender.com"
embedded = true
name = "trade-in-latest"
handle = "trade-in-latest"

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://trade-latest.onrender.com/auth/callback",
  "https://trade-latest.onrender.com/auth/shopify/callback",
  "https://trade-latest.onrender.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "rohit-cybersify.myshopify.com"
automatically_update_urls_on_dev = true
